<?php 
function _single_post_styles() {
    if (!defined('FW')) return; // prevent fatal error when the framework is not active
        
    $single_background_color = fw_get_db_settings_option('single_background_color');
    $single_accent_color = fw_get_db_settings_option('single_accent_color');?>
    
    <style>body{background-color:<?php echo esc_html($single_background_color)?>;color:<?php echo esc_html($single_accent_color)?>}header .social-media-header ul li a,header nav.navbar.navbar-fixed ul.nav>li>a,.navbar .navbar-search-box-icon .search-icon{color:<?php echo esc_html($single_accent_color)?>}hr{border-top:2px solid <?php echo esc_html($single_accent_color)?>}.dot2,#header_top_left ul>li>a:before,nav.navbar ul.nav>li>a:before,.navbar-search-box .navbar-search-box-button .button-blue{background:<?php echo esc_html($single_accent_color)?>}.navbar-search-box{background-color:<?php echo esc_html($single_background_color)?>}#search-box input[type="search"]{color:<?php echo esc_html($single_accent_color)?>;border-bottom:2px solid <?php echo esc_html($single_accent_color)?>}.navbar .navbar-search-box-icon .search-icon i:hover,.navbar .navbar-search-box-icon .search-icon i:focus,.navbar .navbar-search-box-icon .search-icon i:active{color:<?php echo esc_html($single_accent_color)?>}header nav.navbar.navbar-fixed .menu-icon span,header nav.navbar.navbar-fixed .menu-icon:hover span,header nav.navbar.navbar-fixed .menu-icon span:before,header nav.navbar.navbar-fixed .menu-icon span:after{background:<?php echo esc_html($single_accent_color)?>!important}.full-menu ul.full-nav li a{color:<?php echo esc_html($single_accent_color)?>}.full-menu ul.full-nav li:hover span,.full-menu ul.full-nav li:hover a{color:<?php echo esc_html($single_accent_color)?>}.menu-icon span:before,.menu-icon span:after{background:<?php echo esc_html($single_accent_color)?>}ul.social li a{color:<?php echo esc_html($single_accent_color)?>}#header_top_left ul>li>a{color:<?php echo esc_html($single_accent_color)?>}header.page-header{border-bottom:2px solid <?php echo esc_html($single_accent_color)?>}.navbar-search-box .navbar-search-box-data ::placeholder{color:<?php echo esc_html($single_accent_color)?>}</style>
<?php }
add_action('wp_footer', '_single_post_styles');